source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NavigationControllerBlurTransition_Example', :exclusive => true do
  pod "NavigationControllerBlurTransition", :path => "../"
end

target 'NavigationControllerBlurTransition_Tests', :exclusive => true do
  pod "NavigationControllerBlurTransition", :path => "../"

  
end
